### ISSUE TITLE
Error while installing dependencies using NPM

### ISSUE THREAD

**Issue by Skeleton22121** [lexiconhq/lexicon#63] opened 2023-12-27 15:48 UTC
Hi, i was trying to deploying the project using the provided documentation, i followed every step until "npm install && npm run generate". Because whenever i do npm install it gives me this error. 

Error: `npm install && npm run generate

> postinstall
> yarn --cwd api install && yarn --cwd frontend install

Usage: yarn [options]

yarn: error: no such option: --cwd
npm ERR! code 2
npm ERR! path /root/lexicon
npm ERR! command failed
npm ERR! command sh -c yarn --cwd api install && yarn --cwd frontend install

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-12-27T15_37_05_734Z-debug-0.log`

NPM Errorlog: 

`0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.2.3
2 info using node@v20.10.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/root/lexicon/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/root/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 15ms
17 timing npm:load:configload Completed in 15ms
18 timing config:load:flatten Completed in 3ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm install
22 verbose argv "install"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/root/.npm/_logs/2023-12-27T15_37_24_012Z-
26 verbose logfile /root/.npm/_logs/2023-12-27T15_37_24_012Z-debug-0.log
27 timing npm:load:logFile Completed in 12ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 50ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile done cleaning log files
33 timing idealTree:init Completed in 51ms
34 timing idealTree:userRequests Completed in 0ms
35 silly idealTree buildDeps
36 timing idealTree:#root Completed in 0ms
37 timing idealTree:buildDeps Completed in 1ms
38 timing idealTree:fixDepFlags Completed in 0ms
39 timing idealTree Completed in 56ms
40 timing arborist:ctor Completed in 0ms
41 timing reify:loadTrees Completed in 86ms
42 timing reify:diffTrees Completed in 4ms
43 silly reify moves {}
44 timing reify:retireShallow Completed in 2ms
45 timing reify:createSparse Completed in 0ms
46 timing reify:loadBundles Completed in 0ms
47 silly audit bulk request {
47 silly audit   '@types/prop-types': [ '15.7.5' ],
47 silly audit   '@types/react': [ '16.14.28' ],
47 silly audit   '@types/scheduler': [ '0.16.2' ],
47 silly audit   'ansi-regex': [ '4.1.1' ],
47 silly audit   'ansi-styles': [ '3.2.1' ],
47 silly audit   camelcase: [ '5.3.1' ],
47 silly audit   chalk: [ '2.4.2' ],
47 silly audit   'supports-color': [ '5.5.0', '6.1.0' ],
47 silly audit   cliui: [ '5.0.0' ],
47 silly audit   'color-convert': [ '1.9.3' ],
47 silly audit   'color-name': [ '1.1.3' ],
47 silly audit   concurrently: [ '5.3.0' ],
47 silly audit   csstype: [ '3.1.0' ],
47 silly audit   'date-fns': [ '2.29.1' ],
47 silly audit   decamelize: [ '1.2.0' ],
47 silly audit   'emoji-regex': [ '7.0.3' ],
47 silly audit   'error-ex': [ '1.3.2' ],
47 silly audit   'escape-string-regexp': [ '1.0.5' ],
47 silly audit   'find-up': [ '3.0.0' ],
47 silly audit   'function-bind': [ '1.1.1' ],
47 silly audit   'get-caller-file': [ '2.0.5' ],
47 silly audit   has: [ '1.0.3' ],
47 silly audit   'has-flag': [ '3.0.0' ],
47 silly audit   'hosted-git-info': [ '2.8.9' ],
47 silly audit   'is-arrayish': [ '0.2.1' ],
47 silly audit   'is-core-module': [ '2.9.0' ],
47 silly audit   'is-fullwidth-code-point': [ '2.0.0' ],
47 silly audit   'json-parse-better-errors': [ '1.0.2' ],
47 silly audit   'locate-path': [ '3.0.0' ],
47 silly audit   lodash: [ '4.17.21' ],
47 silly audit   'normalize-package-data': [ '2.5.0' ],
47 silly audit   'p-limit': [ '2.3.0' ],
47 silly audit   'p-locate': [ '3.0.0' ],
47 silly audit   'p-try': [ '2.2.0' ],
47 silly audit   'parse-json': [ '4.0.0' ],
47 silly audit   'path-exists': [ '3.0.0' ],
47 silly audit   'path-parse': [ '1.0.7' ],
47 silly audit   pify: [ '3.0.0' ],
47 silly audit   'read-pkg': [ '4.0.1' ],
47 silly audit   'require-directory': [ '2.1.1' ],
47 silly audit   'require-main-filename': [ '2.0.0' ],
47 silly audit   resolve: [ '1.22.1' ],
47 silly audit   rxjs: [ '6.6.7' ],
47 silly audit   semver: [ '5.7.2' ],
47 silly audit   'set-blocking': [ '2.0.0' ],
47 silly audit   'spawn-command': [ '0.0.2-1' ],
47 silly audit   'spdx-correct': [ '3.1.1' ],
47 silly audit   'spdx-exceptions': [ '2.3.0' ],
47 silly audit   'spdx-expression-parse': [ '3.0.1' ],
47 silly audit   'spdx-license-ids': [ '3.0.11' ],
47 silly audit   'string-width': [ '3.1.0' ],
47 silly audit   'strip-ansi': [ '5.2.0' ],
47 silly audit   'supports-preserve-symlinks-flag': [ '1.0.0' ],
47 silly audit   'tree-kill': [ '1.2.2' ],
47 silly audit   tslib: [ '1.14.1' ],
47 silly audit   'validate-npm-package-license': [ '3.0.4' ],
47 silly audit   'which-module': [ '2.0.0' ],
47 silly audit   'wrap-ansi': [ '5.1.0' ],
47 silly audit   y18n: [ '4.0.3' ],
47 silly audit   yargs: [ '13.3.2' ],
47 silly audit   'yargs-parser': [ '13.1.2' ]
47 silly audit }
48 timing reify:unpack Completed in 3ms
49 timing reify:unretire Completed in 43ms
50 timing build:queue Completed in 0ms
51 timing build:deps Completed in 0ms
52 timing build Completed in 1ms
53 timing reify:build Completed in 1ms
54 timing reify:trash Completed in 0ms
55 timing reify:save Completed in 32ms
56 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 301ms
57 timing auditReport:getReport Completed in 306ms
58 silly audit report {}
59 timing auditReport:init Completed in 0ms
60 timing reify:audit Completed in 307ms
61 timing reify Completed in 419ms
62 timing command:install Completed in 646ms
63 verbose stack Error: command failed
63 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
63 verbose stack     at ChildProcess.emit (node:events:514:28)
63 verbose stack     at maybeClose (node:internal/child_process:1105:16)
63 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
64 verbose cwd /root/lexicon
65 verbose Linux 5.4.0-105-generic
66 verbose node v20.10.0
67 verbose npm  v10.2.3
68 error code 2
69 error path /root/lexicon
70 error command failed
71 error command sh -c yarn --cwd api install && yarn --cwd frontend install
72 verbose exit 2
73 timing npm Completed in 900ms
74 verbose code 2`

**Comment by starjustice** [comment] 2024-01-02 04:01
Hey @Skeleton22121, I just wanted to confirm. Have you installed Yarn on your local machine? If not, you can try installing it with the following command: `npm install --global yarn`.

**Comment by Kinostrome** [comment] 2024-03-13 08:31
Hey @Skeleton22121, since it has been several months since we have heard from you about this issue, we will soon close it as resolved.

Please let us know if you have further questions.

**Comment by Kinostrome** [comment] 2024-04-03 04:35
Hey @starjustice, I think you were on track here. From looking at the logs above, this user appears to be on a Linux-based distro.

Some of those distros classically have problems with tools like `node` and `yarn` since running a command like `apt-get install yarn` will actually install an unrelated tool called `cmdtest`, which adds a binary to the `PATH` called `yarn` (that does not have a `--cwd` option).

Here is a [GitHub issue](https://github.com/yarnpkg/yarn/issues/3189) describing someone else's issues with this.

---

On that note, closing this since we haven't heard from the poster, and it looks like this is the cause.

**Closed by Kinostrome** 2024-04-03 04:35 UTC
